application: onesmallpage
version: 1
runtime: python
api_version: 1

handlers: 
-    url: /admin/.*
     script: etext.py

-    url: /
     script: onesmallpage.py  
                                
-   url: /search
    script: onesmallpage.py
    
-   url: /start
    script: onesmallpage.py
    
-   url: /add-reader
    script: onesmallpage.py
    
-   url: /daemon-1
    script: onesmallpage.py